# Generated by Django 5.2.12 on 2026-03-17 21:47

import courses.models
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255, unique=True)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=255, unique=True)),
                ('description', models.TextField(blank=True)),
                ('course_type', models.CharField(choices=[('full', 'Полноценный'), ('simple', 'Неполный')], max_length=10)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('position', 'id'),
                'indexes': [models.Index(fields=['course_type', 'is_active'], name='courses_cou_course__a77db8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('material_type', models.CharField(choices=[('lecture', 'Лекция'), ('presentation', 'Презентация'), ('document', 'Документ'), ('test', 'Тест'), ('other', 'Другое')], max_length=20)),
                ('description', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=False)),
                ('free_preview', models.BooleanField(default=False)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.course')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='LectureMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True)),
                ('duration_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lecture_data', to='courses.material')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DocumentMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_format', models.CharField(choices=[('pdf', 'PDF'), ('doc', 'DOC'), ('docx', 'DOCX'), ('xls', 'XLS'), ('xlsx', 'XLSX'), ('txt', 'TXT'), ('other', 'Другое')], default='other', max_length=10)),
                ('extracted_text', models.TextField(blank=True)),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document_data', to='courses.material')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaterialFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to='courses.material')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='courses.materialfolder')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='MaterialFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('file', models.FileField(upload_to=courses.models.material_file_upload_to)),
                ('file_role', models.CharField(choices=[('main', 'Основной файл'), ('attachment', 'Вложение'), ('image', 'Изображение'), ('other', 'Другое')], default='attachment', max_length=20)),
                ('position', models.PositiveIntegerField(default=0)),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='courses.material')),
                ('folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files', to='courses.materialfolder')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='PresentationMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('speaker_notes', models.TextField(blank=True)),
                ('slides_count', models.PositiveIntegerField(blank=True, null=True)),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='presentation_data', to='courses.material')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('position', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semesters', to='courses.course')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='courses.semester')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.AddField(
            model_name='material',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.subject'),
        ),
        migrations.CreateModel(
            name='TestMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('time_limit_minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('attempts_limit', models.PositiveIntegerField(blank=True, help_text='NULL = без ограничения', null=True)),
                ('passing_percentage', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('shuffle_questions', models.BooleanField(default=False)),
                ('show_correct_answers_after_submit', models.BooleanField(default=False)),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_data', to='courses.material')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='TestQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.TextField()),
                ('question_type', models.CharField(choices=[('single', 'Один вариант'), ('multiple', 'Несколько вариантов'), ('text', 'Текстовый ответ')], default='single', max_length=20)),
                ('explanation', models.TextField(blank=True)),
                ('points', models.PositiveIntegerField(default=1)),
                ('position', models.PositiveIntegerField(default=0)),
                ('correct_text_answers', models.JSONField(blank=True, default=list)),
                ('case_sensitive', models.BooleanField(default=False)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='courses.testmaterial')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='TestAnswerOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=1000)),
                ('is_correct', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='courses.testquestion')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('position', models.PositiveIntegerField(default=0)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='root_topics', to='courses.course')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='topics', to='courses.subject')),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.AddField(
            model_name='material',
            name='topic',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='courses.topic'),
        ),
        migrations.AddConstraint(
            model_name='materialfolder',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('material', 'title'), name='uq_root_folder_title'),
        ),
        migrations.AddConstraint(
            model_name='materialfolder',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('parent', 'title'), name='uq_child_folder_title'),
        ),
        migrations.AddConstraint(
            model_name='materialfolder',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('material', 'position'), name='uq_root_folder_pos'),
        ),
        migrations.AddConstraint(
            model_name='materialfolder',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('parent', 'position'), name='uq_child_folder_pos'),
        ),
        migrations.AddConstraint(
            model_name='materialfile',
            constraint=models.UniqueConstraint(condition=models.Q(('folder__isnull', True)), fields=('material', 'position'), name='uq_root_file_pos'),
        ),
        migrations.AddConstraint(
            model_name='materialfile',
            constraint=models.UniqueConstraint(condition=models.Q(('folder__isnull', False)), fields=('folder', 'position'), name='uq_child_file_pos'),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(fields=('course', 'title'), name='uq_semester_course_title'),
        ),
        migrations.AddConstraint(
            model_name='semester',
            constraint=models.UniqueConstraint(fields=('course', 'position'), name='uq_semester_course_pos'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('semester', 'title'), name='uq_subject_sem_title'),
        ),
        migrations.AddConstraint(
            model_name='subject',
            constraint=models.UniqueConstraint(fields=('semester', 'position'), name='uq_subject_sem_pos'),
        ),
        migrations.AddConstraint(
            model_name='testquestion',
            constraint=models.UniqueConstraint(fields=('test', 'position'), name='uq_test_question_pos'),
        ),
        migrations.AddConstraint(
            model_name='testansweroption',
            constraint=models.UniqueConstraint(fields=('question', 'position'), name='uq_question_option_pos'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('course__isnull', False), ('subject__isnull', True)), models.Q(('course__isnull', True), ('subject__isnull', False)), _connector='OR'), name='topic_one_parent'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', False)), fields=('course', 'title'), name='uq_topic_course_title'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(condition=models.Q(('subject__isnull', False)), fields=('subject', 'title'), name='uq_topic_subject_title'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', False)), fields=('course', 'position'), name='uq_topic_course_pos'),
        ),
        migrations.AddConstraint(
            model_name='topic',
            constraint=models.UniqueConstraint(condition=models.Q(('subject__isnull', False)), fields=('subject', 'position'), name='uq_topic_subject_pos'),
        ),
        migrations.AddIndex(
            model_name='material',
            index=models.Index(fields=['material_type', 'is_published'], name='courses_mat_materia_fb52c8_idx'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('course__isnull', False), ('subject__isnull', True), ('topic__isnull', True)), models.Q(('course__isnull', True), ('subject__isnull', False), ('topic__isnull', True)), models.Q(('course__isnull', True), ('subject__isnull', True), ('topic__isnull', False)), _connector='OR'), name='material_one_parent'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', False)), fields=('course', 'title'), name='uq_mat_course_title'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(condition=models.Q(('subject__isnull', False)), fields=('subject', 'title'), name='uq_mat_subject_title'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(condition=models.Q(('topic__isnull', False)), fields=('topic', 'title'), name='uq_mat_topic_title'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(condition=models.Q(('course__isnull', False)), fields=('course', 'position'), name='uq_mat_course_pos'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(condition=models.Q(('subject__isnull', False)), fields=('subject', 'position'), name='uq_mat_subject_pos'),
        ),
        migrations.AddConstraint(
            model_name='material',
            constraint=models.UniqueConstraint(condition=models.Q(('topic__isnull', False)), fields=('topic', 'position'), name='uq_mat_topic_pos'),
        ),
    ]
